version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
    target-branch: main
    groups:
      nuget-all:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: main
    groups:
      actions-all:
        patterns:
          - "*"
